### ISSUE TITLE
Bug with malformed utf8

### ISSUE THREAD

**Issue by Tragen** [OTRS/OTRSCloneDB#6]
We have some entries in our database where we get an error about malformed utf8.

When you look at Base.pm line 322, you try to print the message you created in
lines 304-307.
I think there is a problem as you create the message with the malformed utf8 and the new value.

But print in line 322 prints out only

> [Sun Aug 26 14:46:31 2018] otrs.Console.pl: Malformed UTF-8 character (unexpected non-continuation byte 0x00, immediately after start byte 0xff) in print at /usr/share/otrs/Kernel/System/CloneDB/Driver/Base.pm line 322.
[Sun Aug 26 14:46:31 2018] otrs.Console.pl: Malformed UTF-8 character (unexpected non-continuation byte 0x03, immediately after start byte 0xf6) in print at /usr/share/otrs/Kernel/System/CloneDB/Driver/Base.pm line 322.
...

The perl docs say that we get this message when we try to print invalid utf8.

I'm using Debian 9. Is there anything I can check?

**Comment by mgruner** [comment]
Hello @Tragen, bugs should be reported via bugzilla only, please. I moved your issue there: https://bugs.otrs.org/show_bug.cgi?id=14047.
